# Change these first
owner: viggy96 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Home Assistant
    url: https://home-assistant.viggy96.me/manifest.json
  - name: Resume
    url: https://www.viggy96.me
  - name: Jellyfin
    url: https://jellyfin.viggy96.me
  - name: Komga
    url: https://komga.viggy96.me
  - name: Nextcloud
    url: https://nextcloud.viggy96.me

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.viggy96.me
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
